const mongoose = require('mongoose');

const ProgressSchema = new mongoose.Schema({
  userId: { type: String, required: true, default: 'default_user' },
  counters: {
    easy: { type: Number, default: 0 },
    medium: { type: Number, default: 0 },
    hard: { type: Number, default: 0 },
    leetcodeContests: { type: Number, default: 0 },
    codeforcesContests: { type: Number, default: 0 },
  },
  checkboxes: {
    type: Map,
    of: Boolean,
    default: {
      dbms: false,
      oops: false,
      cn: false,
      os: false,
      pandas: false,
      numpy: false,
      matplotlib: false,
      seaborn: false,
      plotly: false,
      sqlalchemy: false,
      scikitlearn: false,
      english: false,
      english_vocabulary: false,
      english_spotting_error: false,
      english_sentence_improvement: false,
      english_comprehension: false,
      english_one_word_substitution: false,
      maths: false,
      maths_time_distance: false,
      maths_number_system: false,
      maths_hcf_lcm: false,
      maths_percentage: false,
      maths_circle: false,
      maths_quadratic_equation: false,
      maths_lines_angles: false,
      maths_trigonometry: false,
      maths_heights_distance: false,
      maths_area_perimeter: false,
      maths_surface_area: false,
      maths_statistics: false,
      science: false,
      science_physics: false,
      science_chemistry: false,
      current_affairs: false,
      pyqs: false,
      dsa_bit_manipulation: false,
      dsa_sorting: false,
      dsa_binary_search: false,
      dsa_binary_search_1d: false,
      dsa_binary_search_2d: false,
      dsa_linkedlist: false,
      dsa_array: false,
      dsa_stacks_queues: false,
      dsa_recursion: false,
      dsa_dynamic_programming: false,
      dsa_trees: false,
      dsa_graphs: false,
      dsa_greedy: false,
      dsa_number_theory: false,
      dsa_important_algorithms: false,
    },
  },
}, { timestamps: true });

module.exports = mongoose.model('Progress', ProgressSchema);